<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Small</formFactors>
    <formFactors>Medium</formFactors>
    <formFactors>Large</formFactors>
    <navType>Standard</navType>
    <tab>standard-home</tab>
    <tab>standard-Chatter</tab>
    <tab>standard-WaveHome</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Quote</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Task</tab>
    <tab>standard-File</tab>
    <tab>standard-ContentNote</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-report</tab>
    <tab>standard-Feed</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-Event</tab>
    <tab>standard-OtherUserProfile</tab>
    <tab>standard-Case</tab>
    <tab>standard-News</tab>
    <tab>standard-ForecastingLightning</tab>
    <tab>standard-EinsteinAnalytics</tab>
    <tab>Vacancy__c</tab>
    <tab>Vacancy1__c</tab>
    <tab>LookUpObject1__c</tab>
    <tab>LookUpObject2__c</tab>
    <tab>Parent__c</tab>
    <tab>Child__c</tab>
    <tab>Student__c</tab>
    <tab>Course__c</tab>
    <tab>StuCourseJunc__c</tab>
    <tab>HBO__c</tab>
    <tab>Job__c</tab>
    <uiType>Lightning</uiType>
</CustomApplication>
